language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

notifications:
  irc: "irc.freenode.org#zftalk.modules"
